# Generated by Django 3.1.5 on 2021-01-24 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMeaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.CharField(max_length=50)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('labels', models.CharField(max_length=100)),
                ('basemeaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.basemeaning')),
            ],
        ),
    ]
